-- Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2018.3 (win64) Build 2405991 Thu Dec  6 23:38:27 MST 2018
-- Date        : Wed Jun 18 01:51:39 2025
-- Host        : LAPTOP-RI3013C8 running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode funcsim {D:/Vaidehi Bhat
--               folder/WiSH_Project/WiSH_Project.srcs/sources_1/bd/design_1/design_1_sim_netlist.vhdl}
-- Design      : design_1
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xc7k70tfbv676-1
-- --------------------------------------------------------------------------------
